# Generated by Django 4.0.6 on 2022-08-08 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeerole',
            options={'managed': True, 'verbose_name': 'role', 'verbose_name_plural': 'roles'},
        ),
        migrations.AlterModelTable(
            name='employee',
            table='employees',
        ),
        migrations.AlterModelTable(
            name='employeerole',
            table='roles',
        ),
    ]
