# Generated by Django 4.0.6 on 2022-08-08 03:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_employee_groups_remove_employee_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employeepermission_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='accounts.employeepermission'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Public identifier'),
        ),
    ]
